service: first-aws-serverless-test

provider: 
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'
