service: first-aws-serverless-test

provider: 
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-webpack
  - serverless-offline

functions:
  hello:
    handler: handler.hello
    events:
      - http: GET /hello
      # - http: 'ANY {proxy+}'
